version: '3.4'

networks:
  lbrynet:
    external: true

services:
###########
## MYSQL ##
###########
## MariaDB is currently not supported and neither is later versions of MySQL this may change.
## https://hub.docker.com/r/_/mariadb/
  mysql:
    image: mysql:5.7.23
    restart: always
    networks:
      lbrynet:
        ipv4_address: 10.5.1.10
        aliases:
          - mysql
    env_file:
      - .env
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/chainquery-optimizations.cnf

################
## Chainquery ##
################
  chainquery:
    build:
      context: .
      target: app
    restart: always
    networks:
      lbrynet:
        ipv4_address: 10.5.1.3
    env_file:
      - ./.env
    labels:
      - "traefik.expose=false"
    expose:
      - 6300
    depends_on:
      - mysql
