version: '3.4'

networks:
  lbry-network:
    external: true

services:
###########
## MYSQL ##
###########
## MariaDB is currently not supported and neither is later versions of MySQL this may change.
## https://hub.docker.com/r/_/mariadb/
  mysql:
    image: mysql:5.7.23
    restart: always
    networks:
      lbry-network:
        ipv4_address: 10.6.1.10
        aliases:
          - mysql
    env_file:
      - .env
    expose:
      - 3306
    ## TODO: I want to find a way that is acceptable to everyone to lock this up
    ## and not share it with everyone at least eventually.
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./stuff/my.cnf:/etc/mysql/conf.d/chainquery-optimizations.cnf

################
## Chainquery ##
################
  chainquery:
    build:
      context: .
      target: app
    restart: always
    networks:
      lbry-network:
        ipv4_address: 10.6.1.3
    env_file:
      - .env
      - ../lbrycrd/.env
    labels:
      - "traefik.expose=false"
    expose:
      - 6300
    ports:
      - 6300:6300
    depends_on:
      - mysql
