{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: {{ .Values.service }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
      - name: {{ template "echo-socket-server.fullname" . }}
        image: enigmacurry/echo-socket-server
        ports:
        - containerPort: 8000
{{- end }}

