{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lbrynet.fullname" . }}
  labels:
    app: {{ template "lbrynet.name" . }}
    chart: {{ template "lbrynet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.daemon_settings  }}
  daemon_settings.yml: {{ toYaml . | quote }}
  {{- end }}
{{- end }}
