{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lbrynet.fullname" . }}
  labels:
    app: {{ template "lbrynet.name" . }}
    chart: {{ template "lbrynet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
  selector:
    app: {{ template "lbrynet.name" . }}
    release: {{ .Release.Name }}
{{- end }}
