{{- if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ .Values.service.certificateIssuer }}
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  {{ if .Values.service.enableHttps }}
  tls:
  - hosts:
    - {{ .Values.service.hostname }}
    secretName: {{ .Values.service.name }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.service.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
{{- end }}
