{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "speech.fullname" . }}
  labels:
    app: {{ template "speech.name" . }}
    chart: {{ template "speech.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: port
      port: {{ .Values.service.port }}
      targetPort: port
  selector:
    app: {{ template "speech.name" . }}
    release: {{ .Release.Name }}
{{- end }}
