{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chainquery.fullname" . }}
  labels:
    app: {{ template "chainquery.name" . }}
    chart: {{ template "chainquery.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
{{- end }}
