dependencies:
  - name: mysql
    alias: chainquery-mysql
    repository: "@stable"
    version: 0.19.0
    condition: chainquery-mysql.enabled,global.chainquery-mysql.enabled
  - name: mysql
    alias: speech-mysql
    repository: "@stable"
    version: 0.19.0
    condition: speech-mysql.enabled,global.speech-mysql.enabled
